name: Sync DEBs from EeveeSpotify

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:  # Allows manual trigger

jobs:
  sync-debs:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Remove old .deb files from the debs/ folder
      - name: Remove old DEB files
        run: |
          rm -f debs/*.deb

      # Step 3: Download new .deb files from the release
      - name: Download new DEBs
        run: |
          mkdir -p debs
          # Replace the following line with the code to download the deb files from EeveeSpotify release
          curl -L -o debs/com.eevee.spotify_5.8.8_iphoneos-arm.deb https://github.com/whoeevee/EeveeSpotify/releases/download/v5.8.8/com.eevee.spotify_5.8.8_iphoneos-arm.deb
          curl -L -o debs/com.eevee.spotify_5.8.8_iphoneos-arm64.deb https://github.com/whoeevee/EeveeSpotify/releases/download/v5.8.8/com.eevee.spotify_5.8.8_iphoneos-arm64.deb

      # Step 4: Generate the packages file
      - name: Create packages file
        run: |
          # Create the Packages file here as you were doing before
          dpkg-scanpackages debs /dev/null | gzip > debs/Packages.gz

      # Step 5: Commit and push the changes to your repository
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://github-actions:${{ secrets.GH_TOKEN }}@github.com/creedx888/sileo-repo.git
          git add debs/ Packages Packages.gz
          git commit -m "Auto-update DEBs from EeveeSpotify"
          git push origin main
