name: Sync arm64 DEBs from EeveeSpotify

on:
  schedule:
    - cron: '0 */12 * * *'  # Runs every 12 hours (UTC)
  release:
    types:
      - published
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  sync-debs:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Remove old arm64 DEB files that match eevee.spotify and swift.protobuf
      - name: Remove old arm64 DEB files
        run: |
          echo "Removing old arm64 DEBs with 'eevee.spotify' or 'swift.protobuf' in the name..."
          # Loop through all deb files in the debs/ folder and delete those that match the pattern
          for deb_file in debs/*.deb; do
            if [[ "$deb_file" == *"eevee.spotify"* ]] || [[ "$deb_file" == *"swift.protobuf"* ]]; then
              echo "Removing $deb_file"
              rm -f "$deb_file"  # Delete the matching file
            fi
          done

      # Step 3: Download arm64 DEBs from EeveeSpotify's latest release
      - name: Download arm64 DEBs from EeveeSpotify
        run: |
          echo "Downloading arm64 DEBs from EeveeSpotify..."
          # Fetch the latest release assets from the EeveeSpotify repo
          API_URL="https://api.github.com/repos/whoeevee/EeveeSpotify/releases/latest"
          
          # Fetch the list of arm64 .deb files from the release
          curl -s $API_URL | jq -r '.assets[] | select(.name | test("iphoneos-arm64.*deb$")) | .browser_download_url' | while read deb_url; do
            wget -P debs/ $deb_url  # Download each arm64 .deb file into the debs/ folder
          done

      # Step 4: Create or update the Packages file in the root directory
      - name: Create or update Packages file for arm64 in root
        run: |
          echo "Creating or updating Packages file..."
          # Ensure only arm64 files are included in the Packages file (output it to the root folder)
          dpkg-scanpackages debs /dev/null > Packages

      # Step 5: Compress the Packages file to create Packages.gz in the root directory
      - name: Create Packages.gz
        run: |
          echo "Creating Packages.gz..."
          # Remove the existing Packages.gz file, if it exists, then create a new one
          rm -f Packages.gz
          gzip -9 Packages

      # Step 6: Commit and push changes to the repository
      - name: Commit and push changes
        run: |
          echo "Committing and pushing changes..."
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://github-actions:${{ secrets.GH_TOKEN }}@github.com/creedx888/repo.git
          git add debs/ Packages Packages.gz
          git commit -m "Auto-update arm64 DEBs from EeveeSpotify"
          git push origin main
