name: Sync DEBs from EeveeSpotify

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:  # Allows manual trigger

jobs:
  sync-debs:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Remove old .deb files from the debs/ folder
      - name: Remove old DEB files
        run: |
          rm -f debs/*.deb

      # Step 3: Download new .deb files from the release
       - name: Download new DEBs
         run: |
           mkdir -p debs
           # Fetch the latest release URL containing .deb files
           LATEST_RELEASE=$(curl -s https://api.github.com/repos/whoeevee/EeveeSpotify/releases/latest | jq -r '.assets[] | select(.name | endswith(".deb")) | .browser_download_url')
           # Download all the .deb files from the latest release
           for URL in $LATEST_RELEASE; do
             wget -P debs/ "$URL"
           done

           
      # Step 4: Generate the packages file
      - name: Create packages file
        run: |
          # Create the Packages file here as you were doing before
          dpkg-scanpackages debs /dev/null | gzip > debs/Packages.gz

      # Step 5: Commit and push the changes to your repository
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://github-actions:${{ secrets.GH_TOKEN }}@github.com/creedx888/repo.git
          git add debs/ Packages Packages.gz
          git commit -m "Auto-update DEBs from EeveeSpotify"
          git push origin main
