name: Sync arm64 DEBs from EeveeSpotify

on:
  schedule:
    - cron: '0 */12 * * *'  # Runs every 12 hours (UTC)
  release:
    types:
      - published
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  sync-debs:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Remove old arm64 DEB files
      - name: Remove old arm64 DEB files
        run: |
          # Loop through all deb files in the debs/ folder and delete those that match the pattern
          for deb_file in debs/*.deb; do
            # Remove files that match "eevee.spotify" or "swift.protobuf" for arm64
            if [[ "$deb_file" == *"eevee.spotify"* ]] || [[ "$deb_file" == *"swift.protobuf"* ]]; then
              echo "Removing $deb_file"
              rm -f "$deb_file"  # Delete the matching file
            fi
          done

      # Step 3: Fetch release assets and download only arm64 .deb files
      - name: Download arm64 DEBs from EeveeSpotify
        run: |
          # Fetch the latest release tag dynamically
          API_URL="https://api.github.com/repos/whoeevee/EeveeSpotify/releases/latest"
          
          # Fetch the list of assets (files) from the latest release
          curl -s $API_URL | jq -r '.assets[] | select(.name | test("iphoneos-arm64.*deb$")) | .browser_download_url' | while read deb_url; do
            # Download each arm64 .deb file into the debs/ folder
            wget -P debs/ $deb_url
          done

      # Step 4: Create or update Packages file and overwrite it
      - name: Create or update Packages file for arm64
        run: |
          # Ensure only arm64 files are included in the Packages file
          dpkg-scanpackages debs /dev/null > debs/Packages

          # Overwrite the Packages.gz file (remove previous one and recreate)
          rm -f debs/Packages.gz
          gzip -9 debs/Packages

      # Step 5: Commit and push changes to the repository
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://github-actions:${{ secrets.GH_TOKEN }}@github.com/creedx888/repo.git
          git add Packages Packages.gz
          git commit -m "Auto-update arm64 DEBs from EeveeSpotify"
          git push origin main
