name: Sync DEBs from EeveeSpotify

on:
  schedule:
    - cron: '0 */12 * * *'  # Runs every 12 hours (UTC)
  release:
    types:
      - published

jobs:
  sync-debs:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Remove old .deb files from the debs/ folder
      - name: Remove old DEB files
        run: |
          rm -f debs/*.deb

      # Step 3: Fetch release assets and download all .deb files
      - name: Download DEBs from EeveeSpotify
        run: |
          # Replace the 'v5.8.8' with the latest release version you want to fetch, or use the latest release dynamically
          RELEASE_VERSION="v5.8.8"
          API_URL="https://api.github.com/repos/whoeevee/EeveeSpotify/releases/tags/$RELEASE_VERSION"
          
          # Fetch the list of assets (files) from the release
          curl -s $API_URL | jq -r '.assets[] | select(.name | endswith(".deb")) | .browser_download_url' | while read deb_url; do
            # Download each .deb file into the debs/ folder
            wget -P debs/ $deb_url
          done

      # Step 4: Create Packages file
      - name: Create Packages file
        run: |
          dpkg-scanpackages debs /dev/null | gzip > debs/Packages.gz

      # Step 5: Commit and push the changes to your repository
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://github-actions:${{ secrets.GH_TOKEN }}@github.com/creedx888/repo.git
          git add debs/ Packages Packages.gz
          git commit -m "Auto-update DEBs from EeveeSpotify"
          git push origin main
